# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centrale', models.CharField(blank=True, max_length=150, verbose_name='Centrale de Distribution')),
                ('depot_repartiteur', models.CharField(blank=True, max_length=150, verbose_name='Dépôt Repartiteur')),
                ('designation', models.CharField(blank=True, max_length=250, verbose_name='Désignation')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('cmm', models.FloatField(blank=True, null=True, verbose_name='Conso. Moyenne Mensuelle')),
                ('quantite', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bons de Commande',
            },
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centrale', models.CharField(blank=True, max_length=150, verbose_name='Centrale de Distribution')),
                ('depot_pharma', models.CharField(blank=True, max_length=150, verbose_name='Dépôt Pharmaceutique')),
                ('dci', models.CharField(blank=True, max_length=250, verbose_name='Nom Générique')),
                ('forme', models.CharField(blank=True, max_length=250, verbose_name='Forme')),
                ('dosage', models.IntegerField(blank=True, null=True, verbose_name='Dosage')),
                ('quantite', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('observations', models.CharField(blank=True, max_length=250, verbose_name='Observations')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bons de Livraison',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commande', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro Commande')),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Communes',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Depots',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('dateofbirth', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('status', models.CharField(blank=True, choices=[('CELIBATAIRE', 'Celibataire'), ('MARIE', 'Marié')], max_length=255, null=True, verbose_name='Statut Matrimonial')),
                ('poste', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poste Occupé')),
                ('direction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direction')),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_entree', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entrees',
            },
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10)),
                ('libelle', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Etats',
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250, unique=True)),
                ('code', models.CharField(blank=True, max_length=250, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Familles',
            },
        ),
        migrations.CreateModel(
            name='FicheStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme', models.CharField(blank=True, max_length=150, verbose_name='Forme')),
                ('cmm', models.FloatField(blank=True, null=True, verbose_name='Conso. Moyenne Mensuelle')),
                ('dosage', models.FloatField(blank=True, null=True, verbose_name='Dosage')),
                ('stockMin', models.IntegerField(blank=True, null=True, verbose_name='Stock Minimal')),
                ('stockMax', models.IntegerField(blank=True, null=True, verbose_name='Stock Maximal')),
                ('conditionnement', models.CharField(blank=True, max_length=150, verbose_name='Conditionnement')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('provenance_destination', models.CharField(blank=True, max_length=150, verbose_name='Provenance/Destination')),
                ('entree', models.IntegerField(blank=True, null=True, verbose_name='Entrées')),
                ('sortie', models.IntegerField(blank=True, null=True, verbose_name='Sorties')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock restant')),
                ('peremption_observation', models.TextField(blank=True, verbose_name='Peremptions/Observations')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fiches de Stock',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('site_web', models.URLField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('boite_postale', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='media/photos')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme', models.CharField(blank=True, max_length=150, verbose_name='Forme')),
                ('dosage', models.FloatField(blank=True, null=True, verbose_name='Dosage')),
                ('quantite', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('prix_unitaire', models.IntegerField(blank=True, null=True, verbose_name='Prix Unitaire')),
                ('prix_total', models.CharField(blank=True, max_length=150, verbose_name='Prix Total')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('peremption', models.TextField(blank=True, verbose_name='Date Peremption')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inventaires',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_commande', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name_plural': 'Lignes_Commandes_Medicaments',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('MaterielMedical', 'MaterielMedical'), ('Medicament', 'Medicament')], default='Medicament', max_length=30, verbose_name='Type')),
                ('nom_generique', models.CharField(max_length=250, unique=True)),
                ('forme', models.CharField(blank=True, max_length=150)),
                ('code', models.CharField(blank=True, max_length=150)),
                ('conditionnement', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('prix_achat', models.IntegerField(blank=True)),
                ('prix_vente', models.IntegerField(blank=True)),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Famille', verbose_name='Famille')),
            ],
            options={
                'verbose_name_plural': 'Medicaments',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('nom_ordon', models.CharField(blank=True, max_length=300)),
                ('url', models.TextField(blank=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero de telephone')),
                ('infos', models.TextField(blank=True, max_length=250, null=True, verbose_name='Infos Supplémentaires')),
                ('ordonance', models.FileField(blank=True, null=True, upload_to='media/ordonnances', verbose_name='Ordonnance numerisée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibilite', models.BooleanField(default=True)),
                ('envoye_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ordonnances',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True)),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('libelle', models.CharField(blank=True, max_length=250)),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
                ('horaires', models.CharField(blank=True, max_length=100, null=True)),
                ('garde', models.BooleanField(default=False)),
                ('agrement', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('nom_gerant', models.CharField(blank=True, max_length=200, null=True)),
                ('site_web', models.URLField(blank=True, max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/photos', verbose_name='Logo')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('boite_postale', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=50, unique=True)),
                ('repere', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, default='0.0', max_length=100)),
                ('latitude', models.CharField(blank=True, default='0.0', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pharmacies',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='media/photos')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centrale', models.CharField(blank=True, max_length=150, verbose_name='Centrale de Distribution')),
                ('depot_pharma', models.CharField(blank=True, max_length=150, verbose_name='Dépôt Pharmaceutique')),
                ('date_cmd', models.DateTimeField(verbose_name='Date de la Commande')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date Reception')),
                ('dci', models.CharField(blank=True, max_length=250, verbose_name='Nom Générique')),
                ('forme', models.CharField(blank=True, max_length=250, verbose_name='Forme')),
                ('dosage', models.IntegerField(blank=True, null=True, verbose_name='Dosage')),
                ('qte_cmdee', models.IntegerField(blank=True, null=True, verbose_name='Qté Cmdée')),
                ('qte_recue', models.IntegerField(blank=True, null=True, verbose_name='Qté Reçue')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Fournisseur', verbose_name='Fournisseur')),
                ('num_cmde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Commande', verbose_name='Numéro Commande')),
            ],
            options={
                'verbose_name_plural': 'Proces Verbaux',
            },
        ),
        migrations.CreateModel(
            name='ProduitHorsUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Fevrier', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Aout', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Decembre', 'Decembre')], max_length=30, verbose_name='Mois')),
                ('designation', models.CharField(blank=True, max_length=250, verbose_name='Designation')),
                ('quantite', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('motif', models.TextField(blank=True, max_length=250, verbose_name='Motif')),
                ('prix', models.IntegerField(blank=True, null=True, verbose_name='Prix')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Produits Hors Usage',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=150, null=True, verbose_name='Biographie')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/photos', verbose_name='Photo de profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True)),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='geststock.Pays', verbose_name='Pays')),
            ],
            options={
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('code_quartier', models.CharField(blank=True, max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Commune', verbose_name='Commune')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Departement', verbose_name='Departement')),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Pays', verbose_name='Pays')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Province', verbose_name='Province')),
            ],
            options={
                'verbose_name_plural': 'Quartiers',
            },
        ),
        migrations.CreateModel(
            name='Reconditionnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=250, verbose_name='Désignation')),
                ('nbre_unite_by_cdt', models.IntegerField(blank=True, null=True, verbose_name="Nbre d'Unité par Conditionnement")),
                ('nbre_unite_by_boite', models.IntegerField(blank=True, null=True, verbose_name="Nbre d'Unité par Boite")),
                ('nbre_theorique_cdt', models.IntegerField(blank=True, null=True, verbose_name='Nbre théorique de cdt')),
                ('nbre_reel_cdt', models.IntegerField(blank=True, null=True, verbose_name='Nbre Réel de cdt')),
                ('perte_exces', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perte ou Exces')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cahier Reconditionnement',
            },
        ),
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Commune', verbose_name='Commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Departement', verbose_name='Departement')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Pays', verbose_name='Pays')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Province', verbose_name='Province')),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Quartier', verbose_name='Quartier')),
            ],
            options={
                'verbose_name_plural': 'Rues',
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(blank=True, max_length=255)),
                ('texte', models.TextField(max_length=250, verbose_name='Contenu')),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sms',
            },
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_sortie', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Medicament')),
            ],
            options={
                'verbose_name_plural': 'Sorties',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=300)),
                ('stock_min', models.IntegerField()),
                ('stock_max', models.IntegerField()),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockMedicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_stock', models.IntegerField()),
                ('alerte_qte', models.CharField(max_length=300)),
                ('disponible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entrees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Entree', verbose_name='Entrees')),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Medicament', verbose_name='Medicament')),
                ('sorties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Sortie', verbose_name='Sorties')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Stock', verbose_name='Stock')),
            ],
            options={
                'verbose_name_plural': 'Stock_Pharmacies_Medicaments',
            },
        ),
        migrations.CreateModel(
            name='TypeEtat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Type_Etats',
            },
        ),
        migrations.CreateModel(
            name='TypeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Types_Messages',
            },
        ),
        migrations.CreateModel(
            name='TypeSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'TypeSms',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ventes',
            },
        ),
        migrations.CreateModel(
            name='VenteMedicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_vendu', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Medicament', verbose_name='Medicament')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Vente', verbose_name='Vente')),
            ],
            options={
                'verbose_name_plural': 'Ventes_Medicaments',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code_ville', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('visibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Pays', verbose_name='Pays')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Province', verbose_name='Province')),
            ],
            options={
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.AddField(
            model_name='vente',
            name='medicament',
            field=models.ManyToManyField(through='geststock.VenteMedicament', to='geststock.Medicament', verbose_name='Medicament'),
        ),
        migrations.AddField(
            model_name='stock',
            name='medicament',
            field=models.ManyToManyField(through='geststock.StockMedicament', to='geststock.Medicament', verbose_name='Medicament'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='qte_vendu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.VenteMedicament'),
        ),
        migrations.AddField(
            model_name='rue',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='quartier',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='profile',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Quartier', verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Quartier', verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='rue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Rue', verbose_name='Rue'),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Pharmacie', verbose_name='Pharmacie'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Quartier', verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='message',
            name='destinataire',
            field=models.ManyToManyField(to='geststock.Pharmacie', verbose_name='destinataires'),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.TypeMessage', verbose_name='Type_Message'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Pharmacie'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Medicament', verbose_name='Medicament'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='dci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Medicament', verbose_name='Nom generique'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Quartier', verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='fichestock',
            name='dci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Medicament', verbose_name='Nom generique'),
        ),
        migrations.AddField(
            model_name='fichestock',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Pharmacie', verbose_name='Pharmacie'),
        ),
        migrations.AddField(
            model_name='fichestock',
            name='zone_stockage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Depot', verbose_name='Zone de Stockage'),
        ),
        migrations.AddField(
            model_name='etat',
            name='type_etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.TypeEtat'),
        ),
        migrations.AddField(
            model_name='entree',
            name='medicament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.Medicament'),
        ),
        migrations.AddField(
            model_name='entree',
            name='qte_cmdee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geststock.LigneCommande'),
        ),
        migrations.AddField(
            model_name='departement',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Pays', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='departement',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='departement',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='commune',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Departement', verbose_name='Departement'),
        ),
        migrations.AddField(
            model_name='commune',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Pays', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='commune',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geststock.Fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='medicament',
            field=models.ManyToManyField(through='geststock.LigneCommande', to='geststock.Medicament', verbose_name='Medicament'),
        ),
    ]
