# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geststock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gprovince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('libelle', models.CharField(blank=True, max_length=250)),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, default='0.0', max_length=100)),
                ('latitude', models.CharField(blank=True, default='0.0', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Gprovinces',
            },
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='media/photos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/photos', verbose_name='Photo de profil'),
        ),
    ]
